name: 'MDXish Processor'
description: 'Process MDX files using MDXish and deploy to GitHub Pages'
inputs:
  github_token:
    description: 'GitHub token'
    required: true
  mdxish_version:
    description: 'Version of MDXish to use'
    required: false
    default: 'latest'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    - run: npm install -g mdxish@${{ inputs.mdxish_version }}
      shell: bash
    - run: mdxish
      shell: bash
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ inputs.github_token }}
        publish_dir: ./dist
